[package]
name = "rsmoji"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Gitmoji, but oxidized!"
readme = "README.md"
repository = "https://github.com/Gabriele-Cutrona/rsmoji"
keywords = ["development-tools", "command-line-utilities"]

[dependencies]
crossterm = "0.29.0"
